export const content = {
  en: {
    heading1: "The Next",
    heading2: "Generation",
    heading3: "Business Card.",
    subHeading: "Tap and Share Your Contact Info.",
    getStartedButton: "Get started",
    commingSoon: "Comming Soon!",
    modalHeading: "Receive Notice When Techhype Launch",
    modalInput: "Email",
    modalButton: "Get Notice",
    modalInputError: "Please enter a valid email",
    ModalConfirmation: "Thank you! We will send you an email when Techhype is launched.",
    submitError: "An error occured, Please try again later",
    menuItem1: "Get Started",
    menuItem2: "How it Works",
    menuItem3: "Reviews",
    menuItem4: "Contact Us",
    howHeading: "How It Works",
    purchaseHeading: "Purchase your Card",
    purchaseText: "After placing your order, you will receive instructions on how to provide us with your logo or design for the card.",
    purchaseButton: "View Products",
    createProfileHeading: "Create Your Profile",
    createProfileText: "Here you can add, edit and enable what you would like to share with your contactless business card.",
    createProfileButton: "Sign Up",
    goHeading: "Tap, Share & Go!",
    goText: "It's that simple! Share who you are and what you do with one quick tap.",
    reviewsHeading: "Reviews",
    reviewsSubHeading: "Hear what others say about Techhype",
    verifiedCustomer: "Verified Customer",
    moreReviewsButton: "More Reviews",
    clientsHeading: "Companies Using Techhype",
    footerHeading: "Links",
    footerLink1: "Get Started",
    footerLink2: "How It Works",
    footerLink3: "Reviews",
    footerLink4: "Contact Us",
    footerLink5: "Login",
    footerInfo: "Contactless Business card using NFC technology to simplify networking and sharing contact details.",
    copyRights: "Copyright ©Techhype 2023. All rights reserved.",
  },
  no: {
    heading1: "Den Neste",
    heading2: "Generasjonen",
    heading3: "Visittkort.",
    subHeading: "Tap og Del Din Kontaktinfo.",
    getStartedButton: "Kom i gang",
    commingSoon: "Kommer Snart!",
    modalHeading: "Motta Varsel Når Techhype Lanseres",
    modalInput: "E-post",
    modalButton: "Få Varsel",
    modalInputError: "Vennligst fyll inn en gyldig E-post",
    ModalConfirmation: "Takk! Vi sender deg en E-post når Techhype er lansert.",
    submitError: "En feil oppstod, vennligst prøv igjen senere",
    menuItem1: "Kom i gang",
    menuItem2: "Hvordan det Fungerer",
    menuItem3: "Anmeldelser",
    menuItem4: "Kontakt Oss",
    howHeading: "Hvordan Det Fungerer",
    purchaseHeading: "Kjøp ditt kort",
    purchaseText: "Etter at du har plassert bestillingen din, vil du motta instruksjoner om hvordan du gir oss logoen din eller designet for kortet.",
    purchaseButton: "Se Produkter",
    createProfileHeading: "Opprett Bruker",
    createProfileText: "Her kan du legge til, redigere og aktivere det du ønsker å dele med ditt kontaktløse visittkort.",
    createProfileButton: "Registrer deg",
    goHeading: "Tap, Del og Gå!",
    goText: "Det er så enkelt! Del hvem du er og hva du gjør med bare ett raskt trykk.",
    reviewsHeading: "Anmeldelser",
    reviewsSubHeading: "Hør hva andre synes om Techhype",
    verifiedCustomer: "Verifisert Kunde",
    moreReviewsButton: "vis mer",
    clientsHeading: "Bedrifter som bruker Techhype",
    footerHeading: "Lenker",
    footerLink1: "Kom i Gang",
    footerLink2: "Hvordan Det Fungerer",
    footerLink3: "Anmeldelser",
    footerLink4: "Kontakt Oss",
    footerLink5: "Logg inn",
    footerInfo: "Kontaktløs visittkort som bruker NFC-teknologi for å forenkle nettverking og deling av kontaktinformasjon.",
    copyRights: "Copyright ©Techhype 2023. Alle rettigheter reservert.",
  },
};
